set shell := ["powershell.exe", "-c"]

# PYTHONPATHに現ディレクトリを設定
export PYTHONPATH := justfile_directory()

PYTHON := "pipenv run python"


[doc("一番最初のvenvの環境構築を行います。")]
[unix]
_create-venv:
  if [ ! -d .venv ]; then \
    {{PYTHON}} -m venv .venv; \
  fi

[windows]
_create-venv:
  if (!(Test-Path -Path ".venv")) { \
    {{PYTHON}} -m venv .venv \
  }

[doc("requirements.txtをvenv環境のパッケージリストに反映させます。")]
install: _create-venv
  {{PYTHON}} -m pip install --upgrade pip; \
  {{PYTHON}} -m pip install -r requirements.txt

[doc("ローカル環境でbackendを実行します。")]
run:
  {{PYTHON}} -m flask --debug run

[doc("本番環境にbackendをデプロイします。")]
deploy:
  {{ VENV }}; \
  zappa status prod | Out-Null; \
  if (echo $?) { \
    zappa update prod \
  } else { \
    zappa deploy prod \
  }

[doc("DBにレシピなどの初期データを設定します。")]
db-init:
  {{PYTHON}} -m flask db init; \
  {{PYTHON}} -m flask db migrate -m "Initial migration."; \
  {{PYTHON}} -m flask db upgrade

[doc("DBファイルをすべて削除します。")]
db-clear:
  rm -r -fo satisfactory.db
  rm -r -fo migrations
